version: '3.8'

services:
  postgres:
    image: postgis/postgis:15-3.3
    environment:
      POSTGRES_DB: real_estate
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5999:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      
  app:
    build: .
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: real_estate
      DB_USER: postgres
      DB_PASSWORD: password
    labels:
      - traefik.enable=true
      - traefik.http.routers.clusters.rule=Host(`clusters.mikeprojects.ru`)
      - traefik.http.routers.clusters.entrypoints=websecure
      - traefik.http.routers.clusters=clusters
      - traefik.http.services.clusters.loadbalancer.server.port=8080
      - traefik.http.routers.clusters.tls=true
      - traefik.http.routers.clusters.tls.certresolver=tlsresolver

volumes:
  postgres_data: 